[build]
builder = "DOCKERFILE"
dockerfilePath = "backend/Dockerfile"

[deploy]
startCommand = "cd backend && node dist/main.js"
healthcheckPath = "/api/health"
restartPolicyType = "on_failure"

[phases.setup]
nixPkgs = ["nodejs", "npm"]

[phases.build]
cmds = [
  "cd backend",
  "npm install",
  "npm run build"
] 